# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Integrated Test

on: [push]

jobs:
  model-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache
      uses: actions/cache@v2
      id: cache
      env: 
        cache-name: download-cache
      with:
        path: |
          ~/.nn_meter
          /home/runner/work/nn-Meter/data/testmodels
        key: ${{hashFiles('nn_meter/configs/predictors.yaml')}}-${{hashFiles('tests/integration_test/test_latency_predictor.py')}}

    - name: Install dependencies
      run: |
        pip install tensorflow==2.6.0
        pip install onnx==1.9.0
        pip install torch==1.9.0
        pip install torchvision==0.10.0
        pip install onnx-simplifier
        
    - name: Install nn-Meter
      run: |
        pip install -U .
        pip install protobuf==3.20.3

    - name: Integration test
      run: python tests/integration_test/test_latency_predictor.py
    
    - name: Diff result with reference
      run: diff tests/integration_test/data/reference_result.txt tests/integration_test/test_result.txt
    
    - name: clean env
      run: rm tests/integration_test/test_result.txt  
        
