# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Integrated Test for Torch Model Based on NNI

on: [push]

jobs:
  torch-model-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache
      uses: actions/cache@v2
      id: cache
      env: 
        cache-name: download-cache
      with:
        path: |
          ~/.nn_meter
          /home/runner/work/nn-Meter/data/testmodels
        key: ${{hashFiles('nn_meter/configs/predictors.yaml')}}-${{hashFiles('tests/integration_test/test_latency_predictor.py')}}

    - name: Install dependencies
      run: |
        pip install torch==1.9.0
        pip install torchvision==0.10.0
        pip install nni==2.5

    - name: Install nn-Meter
      run: pip install -U .

    - name: Integration test
      run: python tests/integration_test/test_latency_predictor_torch.py --apply-nni
    
    - name: Diff result with reference
      run: diff tests/integration_test/data/reference_result_nni_based_torch.txt tests/integration_test/test_result_nni_based_torch.txt
        
    - name: clean env
      run: rm tests/integration_test/test_result_nni_based_torch.txt
